### ISSUE TITLE
Online validation errors

### ISSUE THREAD

**Issue by StefanoRaggi** [oanda/v20-openapi#1]
Hi, I am currently adding support for the new Oanda v20 REST API to the [LEAN Engine](https://github.com/QuantConnect/Lean) and I just noticed a few validation errors on the v20 JSON file, using the [swagger online validator](https://generator.swagger.io/).

Here is the link for the error output: https://online.swagger.io/validator/debug?url=https://raw.githubusercontent.com/oanda/v20-openapi/master/json/v20.json

I'm not sure if this could cause any problems with the generated C# code, but just wanted to let you know about it.

**Comment by dmpettyp** [comment]
Hi Stefano,

Thanks for the input, I've fixed up the spec and committed it. It should pass now with no errors.

Let me know how you are progressing, I'm interested to see what you are able to generate. I know for certain there are more OANDA API clients out there who are interested in C# bindings

Dave

**Comment by StefanoRaggi** [comment]
Thank you Dave, I'll regenerate the C# code and let you know.

I found a small typo here:
https://github.com/oanda/v20-openapi/blob/master/json/v20.json#L175
